# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: metadata_api.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'metadata_api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from xmtpv4.envelopes import envelopes_pb2 as xmtpv4_dot_envelopes_dot_envelopes__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12metadata_api.proto\x12\x18xmtp.xmtpv4.metadata_api\x1a\x1cgoogle/api/annotations.proto\x1a xmtpv4/envelopes/envelopes.proto\"\x16\n\x14GetSyncCursorRequest\"K\n\x15GetSyncCursorResponse\x12\x32\n\x0blatest_sync\x18\x01 \x01(\x0b\x32\x1d.xmtp.xmtpv4.envelopes.Cursor\"\x13\n\x11GetVersionRequest\"%\n\x12GetVersionResponse\x12\x0f\n\x07version\x18\x01 \x01(\t2\xea\x03\n\x0bMetadataApi\x12\x9d\x01\n\rGetSyncCursor\x12..xmtp.xmtpv4.metadata_api.GetSyncCursorRequest\x1a/.xmtp.xmtpv4.metadata_api.GetSyncCursorResponse\"+\x82\xd3\xe4\x93\x02%\" /mls/v2/metadata/get-sync-cursor:\x01*\x12\xab\x01\n\x13SubscribeSyncCursor\x12..xmtp.xmtpv4.metadata_api.GetSyncCursorRequest\x1a/.xmtp.xmtpv4.metadata_api.GetSyncCursorResponse\"1\x82\xd3\xe4\x93\x02+\"&/mls/v2/metadata/subscribe-sync-cursor:\x01*0\x01\x12\x8c\x01\n\nGetVersion\x12+.xmtp.xmtpv4.metadata_api.GetVersionRequest\x1a,.xmtp.xmtpv4.metadata_api.GetVersionResponse\"#\x82\xd3\xe4\x93\x02\x1d\"\x18/mls/v2/metadata/version:\x01*B1Z/github.com/xmtp/proto/v3/go/xmtpv4/metadata_apib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'metadata_api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z/github.com/xmtp/proto/v3/go/xmtpv4/metadata_api'
  _globals['_METADATAAPI'].methods_by_name['GetSyncCursor']._loaded_options = None
  _globals['_METADATAAPI'].methods_by_name['GetSyncCursor']._serialized_options = b'\202\323\344\223\002%\" /mls/v2/metadata/get-sync-cursor:\001*'
  _globals['_METADATAAPI'].methods_by_name['SubscribeSyncCursor']._loaded_options = None
  _globals['_METADATAAPI'].methods_by_name['SubscribeSyncCursor']._serialized_options = b'\202\323\344\223\002+\"&/mls/v2/metadata/subscribe-sync-cursor:\001*'
  _globals['_METADATAAPI'].methods_by_name['GetVersion']._loaded_options = None
  _globals['_METADATAAPI'].methods_by_name['GetVersion']._serialized_options = b'\202\323\344\223\002\035\"\030/mls/v2/metadata/version:\001*'
  _globals['_GETSYNCCURSORREQUEST']._serialized_start=112
  _globals['_GETSYNCCURSORREQUEST']._serialized_end=134
  _globals['_GETSYNCCURSORRESPONSE']._serialized_start=136
  _globals['_GETSYNCCURSORRESPONSE']._serialized_end=211
  _globals['_GETVERSIONREQUEST']._serialized_start=213
  _globals['_GETVERSIONREQUEST']._serialized_end=232
  _globals['_GETVERSIONRESPONSE']._serialized_start=234
  _globals['_GETVERSIONRESPONSE']._serialized_end=271
  _globals['_METADATAAPI']._serialized_start=274
  _globals['_METADATAAPI']._serialized_end=764
# @@protoc_insertion_point(module_scope)
