# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto.xmtpv4.metadata_api import metadata_api_pb2 as xmtpv4_dot_metadata__api_dot_metadata__api__pb2


class MetadataApiStub(object):
    """Metadata for distributed tracing, debugging and synchronization
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSyncCursor = channel.unary_unary(
                '/xmtp.xmtpv4.metadata_api.MetadataApi/GetSyncCursor',
                request_serializer=xmtpv4_dot_metadata__api_dot_metadata__api__pb2.GetSyncCursorRequest.SerializeToString,
                response_deserializer=xmtpv4_dot_metadata__api_dot_metadata__api__pb2.GetSyncCursorResponse.FromString,
                _registered_method=True)
        self.SubscribeSyncCursor = channel.unary_stream(
                '/xmtp.xmtpv4.metadata_api.MetadataApi/SubscribeSyncCursor',
                request_serializer=xmtpv4_dot_metadata__api_dot_metadata__api__pb2.GetSyncCursorRequest.SerializeToString,
                response_deserializer=xmtpv4_dot_metadata__api_dot_metadata__api__pb2.GetSyncCursorResponse.FromString,
                _registered_method=True)
        self.GetVersion = channel.unary_unary(
                '/xmtp.xmtpv4.metadata_api.MetadataApi/GetVersion',
                request_serializer=xmtpv4_dot_metadata__api_dot_metadata__api__pb2.GetVersionRequest.SerializeToString,
                response_deserializer=xmtpv4_dot_metadata__api_dot_metadata__api__pb2.GetVersionResponse.FromString,
                _registered_method=True)
        self.GetPayerInfo = channel.unary_unary(
                '/xmtp.xmtpv4.metadata_api.MetadataApi/GetPayerInfo',
                request_serializer=xmtpv4_dot_metadata__api_dot_metadata__api__pb2.GetPayerInfoRequest.SerializeToString,
                response_deserializer=xmtpv4_dot_metadata__api_dot_metadata__api__pb2.GetPayerInfoResponse.FromString,
                _registered_method=True)


class MetadataApiServicer(object):
    """Metadata for distributed tracing, debugging and synchronization
    """

    def GetSyncCursor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeSyncCursor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPayerInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MetadataApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSyncCursor': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSyncCursor,
                    request_deserializer=xmtpv4_dot_metadata__api_dot_metadata__api__pb2.GetSyncCursorRequest.FromString,
                    response_serializer=xmtpv4_dot_metadata__api_dot_metadata__api__pb2.GetSyncCursorResponse.SerializeToString,
            ),
            'SubscribeSyncCursor': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeSyncCursor,
                    request_deserializer=xmtpv4_dot_metadata__api_dot_metadata__api__pb2.GetSyncCursorRequest.FromString,
                    response_serializer=xmtpv4_dot_metadata__api_dot_metadata__api__pb2.GetSyncCursorResponse.SerializeToString,
            ),
            'GetVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVersion,
                    request_deserializer=xmtpv4_dot_metadata__api_dot_metadata__api__pb2.GetVersionRequest.FromString,
                    response_serializer=xmtpv4_dot_metadata__api_dot_metadata__api__pb2.GetVersionResponse.SerializeToString,
            ),
            'GetPayerInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPayerInfo,
                    request_deserializer=xmtpv4_dot_metadata__api_dot_metadata__api__pb2.GetPayerInfoRequest.FromString,
                    response_serializer=xmtpv4_dot_metadata__api_dot_metadata__api__pb2.GetPayerInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'xmtp.xmtpv4.metadata_api.MetadataApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('xmtp.xmtpv4.metadata_api.MetadataApi', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MetadataApi(object):
    """Metadata for distributed tracing, debugging and synchronization
    """

    @staticmethod
    def GetSyncCursor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xmtp.xmtpv4.metadata_api.MetadataApi/GetSyncCursor',
            xmtpv4_dot_metadata__api_dot_metadata__api__pb2.GetSyncCursorRequest.SerializeToString,
            xmtpv4_dot_metadata__api_dot_metadata__api__pb2.GetSyncCursorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeSyncCursor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/xmtp.xmtpv4.metadata_api.MetadataApi/SubscribeSyncCursor',
            xmtpv4_dot_metadata__api_dot_metadata__api__pb2.GetSyncCursorRequest.SerializeToString,
            xmtpv4_dot_metadata__api_dot_metadata__api__pb2.GetSyncCursorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xmtp.xmtpv4.metadata_api.MetadataApi/GetVersion',
            xmtpv4_dot_metadata__api_dot_metadata__api__pb2.GetVersionRequest.SerializeToString,
            xmtpv4_dot_metadata__api_dot_metadata__api__pb2.GetVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPayerInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xmtp.xmtpv4.metadata_api.MetadataApi/GetPayerInfo',
            xmtpv4_dot_metadata__api_dot_metadata__api__pb2.GetPayerInfoRequest.SerializeToString,
            xmtpv4_dot_metadata__api_dot_metadata__api__pb2.GetPayerInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
