# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: xmtpv4/payer_api/payer_api.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'xmtpv4/payer_api/payer_api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from proto.xmtpv4.envelopes import envelopes_pb2 as xmtpv4_dot_envelopes_dot_envelopes__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n xmtpv4/payer_api/payer_api.proto\x12\x15xmtp.xmtpv4.payer_api\x1a\x1cgoogle/api/annotations.proto\x1a xmtpv4/envelopes/envelopes.proto\"d\n\x1dPublishClientEnvelopesRequest\x12\x43\n\tenvelopes\x18\x01 \x03(\x0b\x32%.xmtp.xmtpv4.envelopes.ClientEnvelopeR\tenvelopes\"~\n\x1ePublishClientEnvelopesResponse\x12\\\n\x14originator_envelopes\x18\x01 \x03(\x0b\x32).xmtp.xmtpv4.envelopes.OriginatorEnvelopeR\x13originatorEnvelopes\"\x16\n\x14GetReaderNodeRequest\"i\n\x15GetReaderNodeResponse\x12&\n\x0freader_node_url\x18\x01 \x01(\tR\rreaderNodeUrl\x12(\n\x10\x62\x61\x63kup_node_urls\x18\x02 \x03(\tR\x0e\x62\x61\x63kupNodeUrls2\xdc\x02\n\x08PayerApi\x12\xb8\x01\n\x16PublishClientEnvelopes\x12\x34.xmtp.xmtpv4.payer_api.PublishClientEnvelopesRequest\x1a\x35.xmtp.xmtpv4.payer_api.PublishClientEnvelopesResponse\"1\x82\xd3\xe4\x93\x02+\"&/mls/v2/payer/publish-client-envelopes:\x01*\x12\x94\x01\n\rGetReaderNode\x12+.xmtp.xmtpv4.payer_api.GetReaderNodeRequest\x1a,.xmtp.xmtpv4.payer_api.GetReaderNodeResponse\"(\x82\xd3\xe4\x93\x02\"\"\x1d/mls/v2/payer/get-reader-node:\x01*B\xca\x01\n\x19\x63om.xmtp.xmtpv4.payer_apiB\rPayerApiProtoP\x01Z,github.com/xmtp/proto/v3/go/xmtpv4/payer_api\xa2\x02\x03XXP\xaa\x02\x14Xmtp.Xmtpv4.PayerApi\xca\x02\x14Xmtp\\Xmtpv4\\PayerApi\xe2\x02 Xmtp\\Xmtpv4\\PayerApi\\GPBMetadata\xea\x02\x16Xmtp::Xmtpv4::PayerApib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'xmtpv4.payer_api.payer_api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031com.xmtp.xmtpv4.payer_apiB\rPayerApiProtoP\001Z,github.com/xmtp/proto/v3/go/xmtpv4/payer_api\242\002\003XXP\252\002\024Xmtp.Xmtpv4.PayerApi\312\002\024Xmtp\\Xmtpv4\\PayerApi\342\002 Xmtp\\Xmtpv4\\PayerApi\\GPBMetadata\352\002\026Xmtp::Xmtpv4::PayerApi'
  _globals['_PAYERAPI'].methods_by_name['PublishClientEnvelopes']._loaded_options = None
  _globals['_PAYERAPI'].methods_by_name['PublishClientEnvelopes']._serialized_options = b'\202\323\344\223\002+\"&/mls/v2/payer/publish-client-envelopes:\001*'
  _globals['_PAYERAPI'].methods_by_name['GetReaderNode']._loaded_options = None
  _globals['_PAYERAPI'].methods_by_name['GetReaderNode']._serialized_options = b'\202\323\344\223\002\"\"\035/mls/v2/payer/get-reader-node:\001*'
  _globals['_PUBLISHCLIENTENVELOPESREQUEST']._serialized_start=123
  _globals['_PUBLISHCLIENTENVELOPESREQUEST']._serialized_end=223
  _globals['_PUBLISHCLIENTENVELOPESRESPONSE']._serialized_start=225
  _globals['_PUBLISHCLIENTENVELOPESRESPONSE']._serialized_end=351
  _globals['_GETREADERNODEREQUEST']._serialized_start=353
  _globals['_GETREADERNODEREQUEST']._serialized_end=375
  _globals['_GETREADERNODERESPONSE']._serialized_start=377
  _globals['_GETREADERNODERESPONSE']._serialized_end=482
  _globals['_PAYERAPI']._serialized_start=485
  _globals['_PAYERAPI']._serialized_end=833
# @@protoc_insertion_point(module_scope)
