# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto.xmtpv4.payer_api import payer_api_pb2 as xmtpv4_dot_payer__api_dot_payer__api__pb2


class PayerApiStub(object):
    """A narrowly scoped API for publishing messages through a payer
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PublishClientEnvelopes = channel.unary_unary(
                '/xmtp.xmtpv4.payer_api.PayerApi/PublishClientEnvelopes',
                request_serializer=xmtpv4_dot_payer__api_dot_payer__api__pb2.PublishClientEnvelopesRequest.SerializeToString,
                response_deserializer=xmtpv4_dot_payer__api_dot_payer__api__pb2.PublishClientEnvelopesResponse.FromString,
                _registered_method=True)
        self.GetReaderNode = channel.unary_unary(
                '/xmtp.xmtpv4.payer_api.PayerApi/GetReaderNode',
                request_serializer=xmtpv4_dot_payer__api_dot_payer__api__pb2.GetReaderNodeRequest.SerializeToString,
                response_deserializer=xmtpv4_dot_payer__api_dot_payer__api__pb2.GetReaderNodeResponse.FromString,
                _registered_method=True)


class PayerApiServicer(object):
    """A narrowly scoped API for publishing messages through a payer
    """

    def PublishClientEnvelopes(self, request, context):
        """Publish envelope
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReaderNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PayerApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PublishClientEnvelopes': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishClientEnvelopes,
                    request_deserializer=xmtpv4_dot_payer__api_dot_payer__api__pb2.PublishClientEnvelopesRequest.FromString,
                    response_serializer=xmtpv4_dot_payer__api_dot_payer__api__pb2.PublishClientEnvelopesResponse.SerializeToString,
            ),
            'GetReaderNode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReaderNode,
                    request_deserializer=xmtpv4_dot_payer__api_dot_payer__api__pb2.GetReaderNodeRequest.FromString,
                    response_serializer=xmtpv4_dot_payer__api_dot_payer__api__pb2.GetReaderNodeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'xmtp.xmtpv4.payer_api.PayerApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('xmtp.xmtpv4.payer_api.PayerApi', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PayerApi(object):
    """A narrowly scoped API for publishing messages through a payer
    """

    @staticmethod
    def PublishClientEnvelopes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xmtp.xmtpv4.payer_api.PayerApi/PublishClientEnvelopes',
            xmtpv4_dot_payer__api_dot_payer__api__pb2.PublishClientEnvelopesRequest.SerializeToString,
            xmtpv4_dot_payer__api_dot_payer__api__pb2.PublishClientEnvelopesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReaderNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xmtp.xmtpv4.payer_api.PayerApi/GetReaderNode',
            xmtpv4_dot_payer__api_dot_payer__api__pb2.GetReaderNodeRequest.SerializeToString,
            xmtpv4_dot_payer__api_dot_payer__api__pb2.GetReaderNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
