# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto.xmtpv4.message_api import misbehavior_api_pb2 as xmtpv4_dot_message__api_dot_misbehavior__api__pb2


class MisbehaviorApiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitMisbehaviorReport = channel.unary_unary(
                '/xmtp.xmtpv4.message_api.MisbehaviorApi/SubmitMisbehaviorReport',
                request_serializer=xmtpv4_dot_message__api_dot_misbehavior__api__pb2.SubmitMisbehaviorReportRequest.SerializeToString,
                response_deserializer=xmtpv4_dot_message__api_dot_misbehavior__api__pb2.SubmitMisbehaviorReportResponse.FromString,
                _registered_method=True)
        self.QueryMisbehaviorReports = channel.unary_unary(
                '/xmtp.xmtpv4.message_api.MisbehaviorApi/QueryMisbehaviorReports',
                request_serializer=xmtpv4_dot_message__api_dot_misbehavior__api__pb2.QueryMisbehaviorReportsRequest.SerializeToString,
                response_deserializer=xmtpv4_dot_message__api_dot_misbehavior__api__pb2.QueryMisbehaviorReportsResponse.FromString,
                _registered_method=True)


class MisbehaviorApiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubmitMisbehaviorReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryMisbehaviorReports(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MisbehaviorApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitMisbehaviorReport': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitMisbehaviorReport,
                    request_deserializer=xmtpv4_dot_message__api_dot_misbehavior__api__pb2.SubmitMisbehaviorReportRequest.FromString,
                    response_serializer=xmtpv4_dot_message__api_dot_misbehavior__api__pb2.SubmitMisbehaviorReportResponse.SerializeToString,
            ),
            'QueryMisbehaviorReports': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryMisbehaviorReports,
                    request_deserializer=xmtpv4_dot_message__api_dot_misbehavior__api__pb2.QueryMisbehaviorReportsRequest.FromString,
                    response_serializer=xmtpv4_dot_message__api_dot_misbehavior__api__pb2.QueryMisbehaviorReportsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'xmtp.xmtpv4.message_api.MisbehaviorApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('xmtp.xmtpv4.message_api.MisbehaviorApi', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MisbehaviorApi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitMisbehaviorReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xmtp.xmtpv4.message_api.MisbehaviorApi/SubmitMisbehaviorReport',
            xmtpv4_dot_message__api_dot_misbehavior__api__pb2.SubmitMisbehaviorReportRequest.SerializeToString,
            xmtpv4_dot_message__api_dot_misbehavior__api__pb2.SubmitMisbehaviorReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryMisbehaviorReports(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xmtp.xmtpv4.message_api.MisbehaviorApi/QueryMisbehaviorReports',
            xmtpv4_dot_message__api_dot_misbehavior__api__pb2.QueryMisbehaviorReportsRequest.SerializeToString,
            xmtpv4_dot_message__api_dot_misbehavior__api__pb2.QueryMisbehaviorReportsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
