# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message_contents/public_key.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'message_contents/public_key.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.message_contents import signature_pb2 as message__contents_dot_signature__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!message_contents/public_key.proto\x12\x15xmtp.message_contents\x1a message_contents/signature.proto\"\xba\x01\n\x11UnsignedPublicKey\x12\x12\n\ncreated_ns\x18\x01 \x01(\x04\x12`\n\x16secp256k1_uncompressed\x18\x03 \x01(\x0b\x32>.xmtp.message_contents.UnsignedPublicKey.Secp256k1UncompressedH\x00\x1a&\n\x15Secp256k1Uncompressed\x12\r\n\x05\x62ytes\x18\x01 \x01(\x0c\x42\x07\n\x05union\"Y\n\x0fSignedPublicKey\x12\x11\n\tkey_bytes\x18\x01 \x01(\x0c\x12\x33\n\tsignature\x18\x02 \x01(\x0b\x32 .xmtp.message_contents.Signature\"\x8e\x01\n\x15SignedPublicKeyBundle\x12<\n\x0cidentity_key\x18\x01 \x01(\x0b\x32&.xmtp.message_contents.SignedPublicKey\x12\x37\n\x07pre_key\x18\x02 \x01(\x0b\x32&.xmtp.message_contents.SignedPublicKey\"\xf1\x01\n\tPublicKey\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x38\n\tsignature\x18\x02 \x01(\x0b\x32 .xmtp.message_contents.SignatureH\x01\x88\x01\x01\x12X\n\x16secp256k1_uncompressed\x18\x03 \x01(\x0b\x32\x36.xmtp.message_contents.PublicKey.Secp256k1UncompressedH\x00\x1a&\n\x15Secp256k1Uncompressed\x12\r\n\x05\x62ytes\x18\x01 \x01(\x0c\x42\x07\n\x05unionB\x0c\n\n_signature\"|\n\x0fPublicKeyBundle\x12\x36\n\x0cidentity_key\x18\x01 \x01(\x0b\x32 .xmtp.message_contents.PublicKey\x12\x31\n\x07pre_key\x18\x02 \x01(\x0b\x32 .xmtp.message_contents.PublicKeyBO\n\x1forg.xmtp.proto.message.contentsZ,github.com/xmtp/proto/v3/go/message_contentsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_contents.public_key_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\037org.xmtp.proto.message.contentsZ,github.com/xmtp/proto/v3/go/message_contents'
  _globals['_UNSIGNEDPUBLICKEY']._serialized_start=95
  _globals['_UNSIGNEDPUBLICKEY']._serialized_end=281
  _globals['_UNSIGNEDPUBLICKEY_SECP256K1UNCOMPRESSED']._serialized_start=234
  _globals['_UNSIGNEDPUBLICKEY_SECP256K1UNCOMPRESSED']._serialized_end=272
  _globals['_SIGNEDPUBLICKEY']._serialized_start=283
  _globals['_SIGNEDPUBLICKEY']._serialized_end=372
  _globals['_SIGNEDPUBLICKEYBUNDLE']._serialized_start=375
  _globals['_SIGNEDPUBLICKEYBUNDLE']._serialized_end=517
  _globals['_PUBLICKEY']._serialized_start=520
  _globals['_PUBLICKEY']._serialized_end=761
  _globals['_PUBLICKEY_SECP256K1UNCOMPRESSED']._serialized_start=234
  _globals['_PUBLICKEY_SECP256K1UNCOMPRESSED']._serialized_end=272
  _globals['_PUBLICKEYBUNDLE']._serialized_start=763
  _globals['_PUBLICKEYBUNDLE']._serialized_end=887
# @@protoc_insertion_point(module_scope)
