# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message_contents/signature.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'message_contents/signature.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n message_contents/signature.proto\x12\x15xmtp.message_contents\"\x99\x02\n\tSignature\x12\x46\n\recdsa_compact\x18\x01 \x01(\x0b\x32-.xmtp.message_contents.Signature.ECDSACompactH\x00\x12S\n\x14wallet_ecdsa_compact\x18\x02 \x01(\x0b\x32\x33.xmtp.message_contents.Signature.WalletECDSACompactH\x00\x1a/\n\x0c\x45\x43\x44SACompact\x12\r\n\x05\x62ytes\x18\x01 \x01(\x0c\x12\x10\n\x08recovery\x18\x02 \x01(\r\x1a\x35\n\x12WalletECDSACompact\x12\r\n\x05\x62ytes\x18\x01 \x01(\x0c\x12\x10\n\x08recovery\x18\x02 \x01(\rB\x07\n\x05unionBO\n\x1forg.xmtp.proto.message.contentsZ,github.com/xmtp/proto/v3/go/message_contentsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_contents.signature_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\037org.xmtp.proto.message.contentsZ,github.com/xmtp/proto/v3/go/message_contents'
  _globals['_SIGNATURE']._serialized_start=60
  _globals['_SIGNATURE']._serialized_end=341
  _globals['_SIGNATURE_ECDSACOMPACT']._serialized_start=230
  _globals['_SIGNATURE_ECDSACOMPACT']._serialized_end=277
  _globals['_SIGNATURE_WALLETECDSACOMPACT']._serialized_start=279
  _globals['_SIGNATURE_WALLETECDSACOMPACT']._serialized_end=332
# @@protoc_insertion_point(module_scope)
