# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mls/api/v1/mls.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'mls/api/v1/mls.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14mls/api/v1/mls.proto\x12\x0fxmtp.mls.api.v1\"!\n\x11GroupMessageInput\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"#\n\x13WelcomeMessageInput\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\".\n\x17UploadKeyPackageRequest\x12\x13\n\x0bkey_package\x18\x01 \x01(\x0c\x42(Z&github.com/xmtp/proto/v3/go/mls/api/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.v1.mls_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z&github.com/xmtp/proto/v3/go/mls/api/v1'
  _globals['_GROUPMESSAGEINPUT']._serialized_start=37
  _globals['_GROUPMESSAGEINPUT']._serialized_end=70
  _globals['_WELCOMEMESSAGEINPUT']._serialized_start=72
  _globals['_WELCOMEMESSAGEINPUT']._serialized_end=107
  _globals['_UPLOADKEYPACKAGEREQUEST']._serialized_start=109
  _globals['_UPLOADKEYPACKAGEREQUEST']._serialized_end=155
# @@protoc_insertion_point(module_scope)
