# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: identity/associations/signature.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'identity/associations/signature.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.message_contents import public_key_pb2 as message__contents_dot_public__key__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%identity/associations/signature.proto\x12\x1axmtp.identity.associations\x1a!message_contents/public_key.proto\"*\n\x19RecoverableEcdsaSignature\x12\r\n\x05\x62ytes\x18\x01 \x01(\x0c\"@\n\x1bRecoverableEd25519Signature\x12\r\n\x05\x62ytes\x18\x01 \x01(\x0c\x12\x12\n\npublic_key\x18\x02 \x01(\x0c\"[\n\x1cSmartContractWalletSignature\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x14\n\x0c\x62lock_number\x18\x02 \x01(\x04\x12\x11\n\tsignature\x18\x03 \x01(\x0c\"z\n\x1bRecoverablePasskeySignature\x12\x12\n\npublic_key\x18\x01 \x01(\x0c\x12\x11\n\tsignature\x18\x02 \x01(\x0c\x12\x1a\n\x12\x61uthenticator_data\x18\x03 \x01(\x0c\x12\x18\n\x10\x63lient_data_json\x18\x04 \x01(\x0c\"\xa3\x01\n\x18LegacyDelegatedSignature\x12=\n\rdelegated_key\x18\x01 \x01(\x0b\x32&.xmtp.message_contents.SignedPublicKey\x12H\n\tsignature\x18\x02 \x01(\x0b\x32\x35.xmtp.identity.associations.RecoverableEcdsaSignature\"\xa4\x03\n\tSignature\x12H\n\x07\x65rc_191\x18\x01 \x01(\x0b\x32\x35.xmtp.identity.associations.RecoverableEcdsaSignatureH\x00\x12L\n\x08\x65rc_6492\x18\x02 \x01(\x0b\x32\x38.xmtp.identity.associations.SmartContractWalletSignatureH\x00\x12S\n\x10installation_key\x18\x03 \x01(\x0b\x32\x37.xmtp.identity.associations.RecoverableEd25519SignatureH\x00\x12Q\n\x11\x64\x65legated_erc_191\x18\x04 \x01(\x0b\x32\x34.xmtp.identity.associations.LegacyDelegatedSignatureH\x00\x12J\n\x07passkey\x18\x05 \x01(\x0b\x32\x37.xmtp.identity.associations.RecoverablePasskeySignatureH\x00\x42\x0b\n\tsignatureBY\n$org.xmtp.proto.identity.associationsZ1github.com/xmtp/proto/v3/go/identity/associationsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'identity.associations.signature_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n$org.xmtp.proto.identity.associationsZ1github.com/xmtp/proto/v3/go/identity/associations'
  _globals['_RECOVERABLEECDSASIGNATURE']._serialized_start=104
  _globals['_RECOVERABLEECDSASIGNATURE']._serialized_end=146
  _globals['_RECOVERABLEED25519SIGNATURE']._serialized_start=148
  _globals['_RECOVERABLEED25519SIGNATURE']._serialized_end=212
  _globals['_SMARTCONTRACTWALLETSIGNATURE']._serialized_start=214
  _globals['_SMARTCONTRACTWALLETSIGNATURE']._serialized_end=305
  _globals['_RECOVERABLEPASSKEYSIGNATURE']._serialized_start=307
  _globals['_RECOVERABLEPASSKEYSIGNATURE']._serialized_end=429
  _globals['_LEGACYDELEGATEDSIGNATURE']._serialized_start=432
  _globals['_LEGACYDELEGATEDSIGNATURE']._serialized_end=595
  _globals['_SIGNATURE']._serialized_start=598
  _globals['_SIGNATURE']._serialized_end=1018
# @@protoc_insertion_point(module_scope)
